options:
  auto-update: true
  quest-check-delay: 60
  autosave-interval: 5
  text-wrap: 32
party:
  max-members: 4
  enabled: true
  autokick: 2
book:
  on-first-join: true
dialogue:
  prefix: '&f'
data:
  player:     ../../data-storage/Quest World/
  questing:   quests/
  dialogue:   dialogues/
  presets:    presets/
  extensions: extensions/
