options:
  auto-update: true
  quest-check-delay: 60
  autosave-interval: 5
  log-level: INFO
party:
  max-members: 4
  enabled: true
book:
  on-first-join: true
dialogue:
  prefix: '&f'
save:
  userdata: data-storage/Quest World/
  questdata: plugins/QuestWorld/quests/